[[ColPack]]
arch = "aarch64"
git-tree-sha1 = "5c63b1994e1cb9296256dc1989cb6e61a314e5cc"
os = "macos"

    [[ColPack.download]]
    sha256 = "264d6129dd90381b9d5eadffbbc9a068d15a23de3124dbadf041626e853953e3"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.aarch64-apple-darwin.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1b777ae8132d7554ca0421a104f34f177b80b2de"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "21c3fad7043838f2cd639c4e1e4ce55fcda09680299e9d05cca925cfd903659f"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.aarch64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21923a87b533fd9272c88c53e41ab73be67004ae"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "4843fcec33d9c946cbc04d8d60a11e1c339c7cd24fecfbb7aeba0d3562771692"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.aarch64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "768d01b83777ec7a5409a4b41d01f0e4795d716d"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "fa1b4f18c1529be8bd04143084d176d5179e8d560e9a5e063652c6b1b2bddd85"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.aarch64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3582e4fe8497eeb165c69b83270b215ecf6c7f26"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "d7d48d20797863bdd17a00eaefab49a8547bd068f57756531180bc4d889d8c32"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.aarch64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1f13eb2925552042447ca662a86f353e61508832"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "ceba9fb31489d8a356809c015bdff9ac6674375b8dbb2a26ffa51ceea18f13c5"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "14e472b7697fc159fde340eedc8348ffb8feca93"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "5a7b7fa93d38c5ea5567a5867009ba7b7571f1f4eeea2c18ae8ccaa835cd01c9"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fad2196289ddeb31ad2c54e3f589a888f70b0492"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "f68793bef256591557817a76b4171619af949e874ad3042348bbbe73ed4289f5"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f252f5a57aa317b8441c4c63c5136c0f5ef9fecd"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "142c2643788c7f93b79e3916d7b387c1d7170c0fda3330f2a393572fc1fdcfbd"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e7b08b0a9faf247fe996058707561393e590fe05"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "7ff946c203a4b9bfd50cd3e6d79b3e44f5a1da34065a014c0c130cf3baf9b53a"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b58181b1b6048c3cc96f7cf8c297f4ae7d99c69"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "11942a27b91baa4e3d426e525f1b50d5e10ecb361d392220b3593c3c698a2f40"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "031c03722dfd1c482a63fe396236edc5aa3917d1"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "690c1364a060aba2a20fbb0933ab967d24d8b0453b6aa9f059f528e988c57334"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[ColPack]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38120ce52513af5ad61d7006e27943fbcf2a678d"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "34ea51da32aa9672323ea9c75392c86f6ee3ad7a0e9ee4c898bffef917b1cc9c"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4e368f08c3768400731ac0933e15d7dd5b8eafcb"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "33707092a7ea38e6a3c8570403394c77633fa23c59261d333afee9838a1497b7"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.i686-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48b226c48394dd0f6164ae91bec322237c9a4b20"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "eced5f2ff86cc2ebdcf3d9b8f39247de51b217f7ac2b6ccbfe055abe7c92708e"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.i686-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da58ec2a4306addb9455823f60e3a53e9cfeeb65"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "6a9b97081ba074993ed87e381dca564c6a6538c0a878752bae574019909123d5"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.i686-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f7fd2628109abbeeb76a17d073cada2bb3b861a7"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "12577c8791bcaef5af82304e309a3c839c3212b197be6d7c439f1720e521e0a9"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.i686-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "adb87545edce8d3de4f216976ec353ee43ce3d7c"
os = "windows"

    [[ColPack.download]]
    sha256 = "cfdb7bd8525648180af1cf9b78eb4b387a0715f627631db8019d3e034d51031c"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.i686-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "192b2ed5506a33c7ab1edf4624d00bf25a8a4294"
os = "windows"

    [[ColPack.download]]
    sha256 = "8328a794e9cf2b252aea576ac8e7b1c3be27ded33c5d82215dc6ab9150c61575"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.i686-w64-mingw32-cxx11.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "449642f7b7c56f9a8fff14f88674b729b590e8aa"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "13430d7d1aa11e63bdf7b80da404b5258cae3174adc8c7ff53617cafae9a84bd"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7941bff32c192c5f0bcb7e0fc252b8e75ca218cd"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "5761cf1c6cbec4578dde5d6e6a78470d15e35941fc1b869558ad3119c071b519"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "798e73d55552dbf6169fee842a27635b352eb9eb"
os = "macos"

    [[ColPack.download]]
    sha256 = "e477f6ca29f9cdf7d9b8e4d96fd8a59029c495f4c9e02c4c22fbeb58be8781f7"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-apple-darwin.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "750cfb1ee92dced800645806f0a31bb925f48255"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "53ae8e27a5ae66ba70a81ab73d392d194a770c0c84d818a836e7b7f7adc076af"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-linux-gnu-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d0504b98980f70c56200317e58aa1728ef0de3c"
libc = "glibc"
os = "linux"

    [[ColPack.download]]
    sha256 = "5f6ca683adb03ef48f6cae70f93968cef015c712e03383037cfa22ad739332d9"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-linux-gnu-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "46ebdf3fe47a497e54cfd4e350ed34cbad8d55e9"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "ec41cb7bf23b3e42127f4f046eaa34227b29cbbe94de92e4fb67e422d244df44"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-linux-musl-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7ba21eafc643defbcea79c40d4d075cd1f310cec"
libc = "musl"
os = "linux"

    [[ColPack.download]]
    sha256 = "e57092ec85d140665663d2d7435f8c4bd11b1a4568a081e14669cd01745e7b18"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-linux-musl-cxx11.tar.gz"
[[ColPack]]
arch = "x86_64"
git-tree-sha1 = "124afc68eb50b9853a48702100778bc5677a9b15"
os = "freebsd"

    [[ColPack.download]]
    sha256 = "f45cfc3f3f83f521ca8703348f13e2dc8721cd8e0753472495d93263e2f825cf"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-unknown-freebsd.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7a6a14c60a84a61a8de9909bba58cdc0a1c99049"
os = "windows"

    [[ColPack.download]]
    sha256 = "71cd6a7df97b72a8258eca18254c092cc2be2446d9ee3f7d55960d524d001769"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[ColPack]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f492665c1d20e0ad777f2de8e100ef882e6c0378"
os = "windows"

    [[ColPack.download]]
    sha256 = "a326cd7a36e3a74523e83d68b2a962f4defeff4e3af7cb41a3c117c83a1d9fc1"
    url = "https://github.com/halleysfifthinc/ColPack_jll.jl/releases/download/ColPack-v0.3.0+1/ColPack.v0.3.0.x86_64-w64-mingw32-cxx11.tar.gz"
